export const indexTextParagraphs = [
  [
    'Vad förde dig till oss idag? Vi får väl anta att funderingar på, eller nyfikenhet kring, någon form av säkerhetslösning till båten är anledningen, får vi försöka gissa att något av nedanstående stämmer in? Vi testar!',
    'Båtlivet är fantastiskt! Oavsett om man tuffar runt mellan öarna i skärgården under en helg eller beger sig ut på längre äventyr, få saker slår frihetskänslan när man tar in naturens skönhet i sitt egna tempo! Men låt oss vara ärliga, livet med båt är inte gratis, oavsett båttyp och storlek. Det är inte heller helt bekymmersfritt, stölderna ökar i samhället och båtar är långt ifrån fredade! ',
    'Materialbristen runtom i världen gör även att väntetiderna på ersättningsprodukter är långa, en stulen motor kan äventyra hela säsongen. En dränerad bränsletank går att fylla på men det är oerhört irriterande och frustrerande, man blir redigt förbannad! Vissa båtägare har kommit fram till en tom brygga, hela båten saknas! Eller så ligger båten en halvmeter under ytan efter en storm för länspumpen gick för fulla muggar till batterierna tog slut. Så låt oss då gissa vilken av alla anledningar som förde dig hit idag!',
  ],
  [
    'Flera försäkringsbolag ger rabatterat pris på premien om en spårsändare finns installerad. Vi samarbetar med olika försäkringsbolag som alla erbjuder rabatterat pris på premien om du har en spårsändare installerad. Kontakta oss för att se om just ditt försäkringsbolag ger rabatt.',
    'Nu kanske du undrar: Vad behövs? Hur fungerar det? Vilka kostnader är inblandade? – De flesta spårsändare är väldigt enkla att installera, de som inte har koppling till en extern strömkälla behöver oftast bara aktiveras via tillverkarens app och sedan är du igång. Många spårsändare har även möjlighet att ställa in ett geografiskt stängsel, ofta kallat ”Geofence”, om spårsändaren förflyttas utanför detta stängsel så informeras du, oftast via samma app. För att de flesta spårsändare skall kunna skicka sin data till dig som användare så krävs ett SIM-kort och ett abonnemang. Kostnaden för detta varierar från tillverkare och beroende på mängden data som förväntas förbrukas varje månad, därtill kommer även engångskostnaden för själva spårsändaren.',
    'Vi hoppas att du blev lite klokare, men nu kanske en ny fundering har dykt upp: Finns det några nackdelar eller svagheter? – Det är alltid en god idé att installera en spårsändare, men det förhindrar inte själva stölden. När du får information från sändaren så har stölden redan skett och både tjuvar och bytet är redan på väg någon helt annanstans, dessutom är det stor risk att åverkan gjorts på båten i övrigt, en krossad ruta, avslitna kablar eller knäckt akter och relingar.',
    'Men spårsändaren ska ju känna av om den förflyttar sig utanför det geografiska stängslet?! Ja det stämmer, och det gör den också genom att uppdatera sin position och kontrollera om denna position befinner sig innanför eller utanför stängslet. Hur ofta den uppdaterar sin position varierar, vissa gör det endast en gång per dygn, andra gör det två eller fyra gånger, vilket innebär att tjuvarna i teorin kan ha upp till 23 timmar på sig att förflytta sig med dina ägodelar! Båten kan även ha slitit sig från sin förtöjning om den legat för boj eller ankare och hinner driva iväg en bra bit innan spårsändaren upptäcker sin nya position.',
    'Ytterligare en svaghet är att vissa spårsändare kommunicerar via 2G/GSM-nätet och GPRS vilket håller på att fasas ut och beräknas släckas ned helt år 2025.',
    'Säljer då Nordic Boat Security denna typ av spårsändare? Nej det gör vi inte! Den spårsändare vi erbjuder kommunicerar via 4G/LTE-nätet och har betydligt tätare uppdateringsfrekvens gällande sin position, vi pratar om realtidsspårning! Denna spårsändare har både ett inbyggt batteri men kopplas även till båtens egna batterier. Vi kan programmera spårsändaren att aktivera våra inbrottslarm om kopplingen till båtens batterier klipps av!',
  ],
  [
    'Som vi nämner ovan så är en spårsändare ett bra alternativ för att hålla koll på var egendomen befinner sig, exempelvis båten, motorn eller vattenskotern och den ökar chansen att få tillbaka egendomen vid en stöld, men den förhindrar oftast inte själva stölden eller den eventuella åverkan som kan uppstå vid stölden.  Ett inbrottslarm är däremot en starkt preventiv åtgärd som syftar till att skrämma bort tjuvarna, påkalla uppmärksamhet och informera dig som båtägare om det pågående inbrottsförsöket.',
    'Rörelsedetektorer och magnetkontakter för båtens dörrar och luckor aktiverar kraftfulla sirener, ljudbarriärer och blixtljus, detta drar till sig uppmärksamheten omgående! Låt inte tjuven arbeta ostört! ',
    'Låter det som något du letar efter? Men du kanske även funderar på hur det är med bevisbördan? Övervakningskameror med inspelning är svaret! Givetvis tillhandahåller vi även detta i vår produktportfölj! Vi har videokameror som levererar bildkvalité från 2 megapixlar upp till 12 megapixlar!',
  ],
  [
    'En del båtägare känner ingen större oro för just inbrott i båten men är däremot intresserade av att veta hur båten mår. Enligt en undersökning som tidningen Båtliv lät genomföra 2019 så svarade 46% att de använder båten max 20 dagar per säsong, är du en av dem?',
    'Har båten tagit in vatten efter ett skyfall? Hur mycket ström är kvar i batteriet för länspumpen? Är den alls i drift?! Känns denna oro bekant? Vi har lösningen som ger lugn och ro! Våra produkter ger dig total kontroll över din båt!',
  ],
  [
    'Genom applikationer får du total kontroll på din båt, det är du som avgör hur mycket du vill kunna ha kontroll över! En spårsändare ger dig ökad chans att återfå en stulen båtmotor men den ger dig även koll på om tonåringen endast tog den där korta svängen med vännerna som utlovat…',
    'Inbrottslarm skrämmer bort tjuven men ger dig även information om att larmet har aktiverats, har du dessutom videokameror installerat på båten så ser du händelsen i realtid samtidigt som inspelningen lagras.',
    'Eller som vi nyligen nämnt, hur mår båten? Tar den in vatten? Hur är batterinivån? Hur är temperaturen? Brinner det? Sådana typer av tankar går enkelt att få svar på!',
  ],
  [
    'Så hur lyckades vi? Stämmer något av ovanstående in på anledningen till ditt besök här idag? Det är möjligt att vi hade fel, men vi kanske skapade en viss fundering och en nyfikenhet hos dig? Kanske vore det inte så dumt med någon form av säkerhetslösning för båten?',
    'Vad kostar inbrottslarmet och övervakningen? Ni visar inga priser om det? Nej det stämmer att vi inte publicerar priserna på de system som vi erbjuder, vi vill nämligen veta mer om dig och din båt först och tillsammans hitta en skräddarsydd lösning som passar ditt behov!',
  ],
];
